### ISSUE TITLE
🟢<ACTIVE>🟢 💰 Bounty: Creator Coin Deeplink Generator WebApp - $100 (500 $RLY) 💰

### ISSUE THREAD

**Issue by RallyCreatorCoins** [CreatorCoinTools/RallyBot#1]
=========================
 
**Bounty: Creator Coin Deeplink Generator**
 
**Status: 🟢 PENDING 🟢**
 
**Reward: 💰750 $RLY💰**
 
**Time Estimate: 3 Hours**

=========================

**Description:** Create a GUI WebApp that generates deeplinks for Rally.io.

 **User Stories:**
As a Creator:

- I want to be able to generate Deeplinks easily.
- I don't know how to code so I don't want to have to manually edit the URL.

**Deeplink Example:**
Input syntax:  `$customlink <CoinName> <CurrencyType> <Amount> <Memo>`
Input example:  `$customlink <FAN> <COINS> <20> <Hero Request for Lunara>`

Output: https://www.rally.io/creator/FAN/?inputType=COINS&amount=20&note=Hero%20Request%20for%20Lunara

**Minimum Requirements:**
- GUI based Deeplink Generator for Rally.io Deeplinks
- Include a "Test" button that links the user to the page to try it.
- Include Validation to ensure the URL works. If not, report error.
- Host the GUI at https://rallybot.app/deeplink
- Include a "Need Help?" Discord Button with the following link: https://discord.gg/R7dHmKA5aJ
- Submit an open public repository with MIT licensing included such that the implementation can be reused

**Include the following parameters:**
1. Dropdown list - Coin Name: "rally.io/creator/<CoinName>" 
2. Buttons - Currency Displayed: `?inputType=<Currency>`  - "COIN" or "USD"
2. Text Input - Amount: `&amount=< >` " - #; of Coins or USD
3. Text Input - Note: `&note=< >` (must include % for spaces)

**To Discuss or Claim this bounty, join the Rally Discord:** https://discord.gg/aPCQYQDQzp

**Docs:**
- None on Deeplinks yet, sorry! 
- https://developer.rally.io/#/

**Comment by iamzubin** [comment]
I would like to work on this issue.

**Comment by iamzubin** [comment]
![image](https://user-images.githubusercontent.com/8392856/106383523-9c42fe80-63ec-11eb-88b0-0bed16fb3635.png)
I've creted a simple mockup on figma, lemme know if it's okay then I'll work on it.

**Comment by iamzubin** [comment]
I worked a litte, got a little busy with some other stuff, I just need to add a drop down support instead of text field
This is usable as is, but would like to improve it further, as it doesn't match the requirements

**Comment by RallyCreatorCoins** [comment]
Paid 1000 $RLY instead as the scope of the project was bigger than anticipated.
